### ISSUE TITLE
Unable to send larger attachments on 16MB

### ISSUE THREAD

**Issue by selva86** [trinker/gmailR#11]
```
gc()
options(java.parameters = "-Xmx4g" )
gmail(to=c("email@gmail.com"), 
      from = "email@gmail.com",
      username = "user",
      password = "pass",
      subject = "test",
      attachment="path/to/zip/file")


Error in .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl,  : 
  Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "<string>", line 11, in <module>
java.lang.OutOfMemoryError: Java heap space
    at java.lang.String.<init>(String.java:339)
    at org.python.core.util.StringUtil.fromBytes(StringUtil.java:44)
    at org.python.core.util.StringUtil.fromBytes(StringUtil.java:64)
    at org.python.core.io.BinaryIOWrapper.readall(BinaryIOWrapper.java:57)
    at org.python.core.io.BinaryIOWrapper.read(BinaryIOWrapper.java:28)
    at org.python.core.PyFile.file_read(PyFile.java:248)
    at org.python.core.PyFile$file_read_exposer.__call__(Unknown Source)
    at org.python.core.PyObject.__call__(PyObject.java:385)
    at org.python.pycode._pyx108.f$0(<string>:24)
    at org.python.pycode._pyx108.call_function(<string>)
    at org.python.core.PyTableCode.call(PyTableCode.java:165)
    at org.python.core.PyCode.call(PyCode.java:18)
    at org.python.core.Py.runCode(Py.java:1204)
    at org.python.core.Py.exec(Py.java:1248)
    at org.python.util.PythonInterpreter
```

**Comment by trinker** [comment]
This package is unsupported.  I think that the CRAN gmailr package maintained by Jim Hester would suit your needs

https://cran.r-project.org/web/packages/gmailr/index.html
